### ISSUE TITLE
7.5 eink problems

### ISSUE THREAD

**Issue by ghost** [ankesreich/eInkDisplayDriver#2]
Hello, I'm using your driver for my projekt. I have read your artikel in the magazine. But after some days I have the problem that it looks more grey than black in some parts. I'm doing always a full refresh and sleep. Maybe you have an idea?

Thanks a lot,
Marc

![20190621_085618](https://user-images.githubusercontent.com/52105612/59964968-90047900-9508-11e9-8d74-c247d2c3c427.jpg)
![20190621_085801](https://user-images.githubusercontent.com/52105612/59964972-95fa5a00-9508-11e9-8aa8-ff8d03a2bf1f.jpg)
![20190621_084644](https://user-images.githubusercontent.com/52105612/59964963-7f540300-9508-11e9-9aa8-2f04ec778d80.jpg)

**Comment by ankesreich** [comment]
Hi Marc,
sorry to hear that you have problems with the color of the display.
I didn' t have that problem, my display has been running now since half a year with good colors.
So I am afraid I cannot help.
When I transferred the code to Java I didn't change anything from the original Waveshare  /  Ben Krasnow's code, just translated it.

The answer of Waveshare to this problem on their Homepage:

Question:Why does the color of e-Paper look a little black or grey? 
Answer: You can try to change the value of Vcom on demo codes.

I don't have any experience with that. Maybe it is a good idea to contact the Waveshare support.. 

Anke
